name: JS Actions

on:
  workflow_dispatch:
#  pull_request:
#    types: [labeled]

jobs:
  actions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: hello-action
        uses: ferdlestier/test_packages@main
